stages:
  - build
  - test
  - deploy
  - cleanup

# It is shared between includes anyway
default:
  retry:
    max: 2
    when:
      - unknown_failure
      - api_failure
      - stuck_or_timeout_failure
      - runner_system_failure
      - runner_unsupported
      - stale_schedule
      - job_execution_timeout
      - unmet_prerequisites
      - scheduler_failure
      - data_integrity_failure

variables:
  GIT_STRATEGY: fetch
  GIT_DEPTH: 1
  TAG_NAME: ${CI_COMMIT_REF_SLUG}
  BACK_IMAGE: node
  BACK_IMAGE_DEV: ${BACK_IMAGE}:18-alpine
  BACK_IMAGE_STABLE: ${BACK_IMAGE}:18-alpine
  FRONT_IMAGE: node
  FRONT_IMAGE_DEV: ${FRONT_IMAGE}:18-alpine
  FRONT_IMAGE_STABLE: ${FRONT_IMAGE}:18-alpine
  FEATURE_DEPLOY_MR_ON_K8S: 1
  KUBERNETES_URL_SUFFIX: "boilerplate.test.thecodingmachine.com"
  #KUBERNETES_PASSWORD_SECRET: "CHANGE-THIS-SECRET" # Define it in gitlab CI/CD variables
#  DEPLOYMENT_PATH: /tcm_deployment/${CI_PROJECT_NAME}
#  DEPLOYMENT_IP: PUT_YOUR_DEPLOYMENT_IP_HERE

include:
  - local: 'gitlab-ci/rules.gitlab-ci.yml'
  - local: 'gitlab-ci/test-back.gitlab-ci.yml'
  - local: 'gitlab-ci/test-front.gitlab-ci.yml'
