include:
  - local: 'gitlab-ci/templates/apps.gitlab-ci.yml'

test back analyze:
  stage: 'test'
  extends:
    - '.app back'
    - '.app back cache-rw'
    - '.MR rules'
  script:
    - yarn lint
    - yarn format:lint
    - yarn test
    - yarn build
  interruptible: true

# TODO : have to be implemented
#back unit test:
#  stage: 'test'
#  extends:
#    - '.app back'
#  variables:
#    # mysql_tests service.
#    MYSQL_ROOT_PASSWORD: root-secret
#    MYSQL_DATABASE: api
#    MYSQL_USER: user
#    MYSQL_PASSWORD: secret
#  services:
#    - name: mariadb:10.11
#      alias: mysql_tests
#  script:
#    - composer run test
#  needs:
#    - 'test back build'
#  rules:
#    - !reference [.except hotfix rules, rules]
#    - when: always
